---
- hosts: "{{ server }}"
  tasks:
  - name: Stop Tomacat
    win_service:
      name: Tomcat6
      state: stopped
  - name: Delete logs
    win_shell:
      Get-ChildItem -Path C:\Program Files (x86)\Apache Software Foundation\Tomcat 6.0\logs  -Include *.log -Recurse | Remove-Item
  - name: Start Tomcat
    win_service:
      name: Tomcat6
      state: started
